# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: 'Azure Pipelines'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm test
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to App Service
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy_Job
    pool:
      name: Azure Pipelines
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifact: 'drop'
        targetPath: '$(Pipeline.Workspace)/drop'
      displayName: 'Download Artifact'

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: 'ARM-connection-dev'
        appType: 'webApp'
        appName: 'web-app-version-2'
        package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
        deploymentMethod: 'zipDeploy'